### ISSUE TITLE
Question: Neue Datenpunkte

### ISSUE THREAD

**Issue by serav993** [marc2016/panasonic-comfort-cloud-client#10]
Hallo, sehr gute Arbeit 👍 
Gibt es noch die Möglichkeit Datenpunkte für den Quiet bzw. Powerful-Betrieb hinzuzufügen ?
Könnte man auch Gerätedaten auslesen, wie zum Beispiel einen eventuellen Errorcode oder die Leistungsaufnahme des Kompressors im Betrieb ?
Über Modbus mit entsprechendem Adapter lassen sich diese Werte auslesen.
Ich frage nur aus Interesse und für eventuelle Anregungen.

**Comment by UwesSmartHome** [comment]
Hallo, woher bekommt man die MODBUS Register. Panasonic ist da auf dem Ohr taub.

**Comment by UwesSmartHome** [comment]
Hallo serav993,

wo findet man die Modbus Register?

**Comment by serav993** [comment]
Hallo,
entschuldige die späte Antwort.

https://cdn.hms-networks.com/docs/librariesprovider11/manuals-design-guides/user-manuals/ac-interfaces/user-manual-inmbspan001i100.pdf?sfvrsn=33150d7_4

Hier sind die Modbusregister zu finden.
Ab Seite 8 ist eine Auflistung. Die funktionieren auch alle. Bevor ich deine geniale Arbeit mit dem WLAN Gateway gefunden habe. Habe ich modbus rtu Gateway + Intesis Box genutzt.
Leider ist der Preis fern ab von gut und böse und ich hatte Glück das so ein Ding "vom Laster viel"
