### ISSUE TITLE
New appVersion again?

### ISSUE THREAD

**Issue by ugumba** [marc2016/panasonic-comfort-cloud-client#12]
Using the npm package, authentication fails - debugging to look at response object reveals "New version app has been published".

Also, is it possible to capture the response message so it can be surfaced in my own exception handler?  At the top level, I can only see generic HTTP status code/text.

Also, the npm package is at version 1.2.0, while the repo is 1.1.7.  Why the discrepancy?

Edit: I just realized I can override appVersion in the ComfortCloudClient constructor, so a package update should not be neccessary - thanks!  My 2 questions above still stand, though.

**Comment by marc2016** [comment]
Hi,
Panasonic is also changing the app version for the interface with a new app. so that you can change and test them quickly, i have added this setting.
I have to look into why the NPM package and the version in git diverge. Thanks for the hint.
The response from the interface is not given out directly by the adapter. Unfortunately, I also have a problem with exception handling. I have to fix that too.

**Comment by nordlings** [comment]
> Edit: I just realized I can override appVersion in the ComfortCloudClient constructor, so a package update should not be neccessary - thanks! My 2 questions above still stand, though.

sorry for noobish question, how do you override the appVersion in the ComfortCloudCloude constructor?
I am doing this without much success:
`const heater = new ComfortCloudClient("1.2.6");`

Getting:
"Error ocured: ServiceError: Request failed with status code 403" 
as response... 

would expect:
"New version app has been published"

**Comment by nordlings** [comment]
> const heater = new ComfortCloudClient("1.2.6");

Figured it out, current default version is 1.18.0 (not 1.26.0). 
When new ComfortCloudClient("1.18.0") I got the same error "New version app has been published" as when not specifying the version override.

New correct version 1.19.0 gave me a working solution again.
