### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by ugumba** [marc2016/panasonic-comfort-cloud-client#14]
My Homey app stopped working because Panasonic seems to have started requiring 2FA. 

Just wanted to highlight this here as it will impact all consumers of this package.

**Comment by nickmurison** [comment]
FYI I did some testing using a proxy, and discovered the auth step works fine if you send a higher app version numbers, I've submitted a PR for this: https://github.com/marc2016/panasonic-comfort-cloud-client/pull/15

**Comment by MACNETWORK** [comment]
Just a thought but I see that Panasonic will allow the use of Google Authenticator for 2FA - and there are a few implementations of that in Node Red. I was using node-red-contrib-panasonic-comfort-cloud but it only works a few times before 'Too Many Requests' pops up. Could this get around the problem?

**Comment by ugumba** [comment]
So 2FA wasn't required - the app version bump was sufficient, and could be accomplished from the app.

However, now authentication is consistently failing again (503s - for multiple users), and Panasonic's official apps have not been updated.

https://community.homey.app/t/app-pro-panasonic-comfort-cloud-alternative/75906/145?u=robert_schmidt

**Comment by marc2016** [comment]
https://github.com/lostfields/python-panasonic-comfort-cloud/issues/93

**Comment by ugumba** [comment]
Thanks, @marc2016, good find!
Is there any chance you'll look into this yourself, for your package?

**Comment by marc2016** [comment]
Yes, I use the client myself and need it :-) I'm currently working on implementing the oauth login for my package.

**Comment by marc2016** [comment]
Works now with version 2.0.0
https://www.npmjs.com/package/panasonic-comfort-cloud-client
