### ISSUE TITLE
HTTP status 412 (precondition failed)

### ISSUE THREAD

**Issue by ugumba** [marc2016/panasonic-comfort-cloud-client#16]
Hi, sorry to interrupt your flow... :-)

As of this morning, my Homey app for PCC receives 412 during authentication.
(It happens at least for another user and myself.)

I can reproduce with this code:
```
import { ComfortCloudClient } from 'panasonic-comfort-cloud-client'

let client = new ComfortCloudClient("1.22.0");
try {
    let token = await client.login("xxx@yyy.zzz", "yaddayaddayadda");
    console.log(token);
}
catch (e)
{
    console.log(e);
}
```

The Android app seems to work fine with the same credentials.  
There was a notification about a change to the authentication flow (a simplification, I think) - this might not be related.

**Comment by xgcssch** [comment]
Same here with NodeRed and node-red-contrib-panasonic-comfort-cloud.

**Comment by bisand** [comment]
> Same here with NodeRed and node-red-contrib-panasonic-comfort-cloud.

FYI: **bisand/node-red-contrib-panasonic-comfort-cloud** is by the way using this library.

**Comment by bisand** [comment]
The login works fine and a token is returned, but when it tries to call getClientId() it fails with "_Request failed with status code 412 Precondition Failed_"
https://github.com/marc2016/panasonic-comfort-cloud-client/blob/528f94b00bfc119e24adff5f078a9dfba4976453/src/ComfortCloudClient.ts#L59

**Comment by pacholoamit** [comment]
Similar to this issue https://github.com/sockless-coding/panasonic_cc/issues/331

**Comment by marc2016** [comment]
If there is a solution, I will implement it as quickly as possible :-)
I am keeping track of the discussion on that issue.

**Comment by marc2016** [comment]
This is the solution I think: https://github.com/sockless-coding/panasonic_cc/pull/336
I will try to implement and test it in my project.

**Comment by hrrrsn** [comment]
If it helps you, my original implementation [was in Javascript](https://gist.github.com/hrrrsn/2b0aa2ab2a0fe3c78d2d9657a4e294a8) before porting to Python.

**Comment by marc2016** [comment]
@hrrrsn thank you, that helped very much! :-)
Issue is fixed in version 2.0.3

**Comment by ugumba** [comment]
Fantastic - thank you both for the quick fix! 
Verified locally with my app, and pushed a new version.

**Comment by nordlings** [comment]
Thanks 😀
