### ISSUE TITLE
Use the package in a command line script

### ISSUE THREAD

**Issue by ronnyandre** [marc2016/panasonic-comfort-cloud-client#3]
Hi, great work on this package!

I was wondering if it was possible to use this package in a Node script that you can run directly in the command line? The reason is that I want to call this script from my home automation system.

**Comment by marc2016** [comment]
Hi,

I've only seen your message now, sorry! :-(

The package should also run in a node application. Which home automation system do you use? I use iobroker and have developed an adapter for it: https://github.com/marc2016/ioBroker.panasonic-comfort-cloud

**Comment by ronnyandre** [comment]
Hi Marc, thanks for replying!

I am helping out my dad with implementing his new HVAC in HomeSeer. As I don't have much knowledge about HS and making plugins, we are doing a workaround using Node-RED to communicate with a script that talks with the HVAC.

However, I first wanted to try your package in a Node script, but I got errors, so I tried another Python package instead, which works OK.

**Comment by marc2016** [comment]
If you want, post the error messages here and I'll have a look :-)

My package based on a Python package. Maybe they are the same.
